### ISSUE TITLE
Can't compile project.

### ISSUE THREAD

**Issue by bacons28** [Eric-liucn/PixelmonSync2#3]
Is there any plan to get back with this project?
I'm realy needing it!

**Comment by ShunL12324** [comment]
should be able to compile, are u using a different version of Pixelmon? If there are compile errors, please create a Pastebin link so that I can check it and see if I can help you ^_-

I will try to maintain this project but cannot guarantee it...

**Comment by bacons28** [comment]
Here it is: https://pastebin.com/P8EiF8LD
I'm very newbie with compile projects, I only need download your project and run gradlew build, right?
I'm trying in 1.12.2.

**Comment by ShunL12324** [comment]
For most plugins, that's all that's required. However, since this plugin imports code from Pixelmon and is linked with Forge, it needs the Forge Gradle environment and the Pixelmon jar file to be compiled. You can check the `buildscript` and `dependencies`  in the build.gradle file. Additionally, I have published a release with the compiled jar file for direct download.
